export type GlossaryItem={term:string,definition:string,lesson?:string};
export const glossary:GlossaryItem[]=[
["Allah","The Arabic name Muslims use for the one true God, the Creator and Sustainer of everything.","tawhid"],
["Islam","Submission to Allah through faith, worship, and living by His guidance.","five-pillars"],
["Muslim","A person who submits to Allah and accepts Islam.","shahada"],
["Shahada","The testimony that there is no deity worthy of worship except Allah and that Muhammad is His Messenger.","shahada"],
["Tawhid","The doctrine of Allah's oneness, especially the exclusivity of worship due to Him.","tawhid"],
["Iman","Faith: belief of the heart expressed through words and actions.","belief"],
["Ihsan","Spiritual excellence: worshipping Allah with awareness that He sees you.","islam-iman-ihsan"],
["Aqidah","The beliefs and creed a Muslim holds about Allah, revelation, and the unseen.","belief"],
["Revelation","Guidance Allah communicates to His prophets, including the Quran.","quran"],
["Prophet","A person chosen by Allah to receive and convey guidance.","prophets"],
["Messenger","A prophet entrusted to convey a revealed message to a people.","prophets"],
["Quran","The scripture revealed to Prophet Muhammad in Arabic and preserved and recited by Muslims.","quran"],
["Sunnah","The prophetic way: the Prophet's teachings, example, approvals, and guidance.","sunnah"],
["Hadith","A report describing something attributed to the Prophet, assessed through scholarly methods.","sunnah"],
["Tafsir","Scholarly explanation and interpretation of the Quran.","reading-quran"],
["Ayah","A verse or sign in the Quran.","quran"],
["Surah","A chapter of the Quran.","quran"],
["Al-Fatihah","The opening chapter of the Quran, recited in every rakah of the formal prayer in mainstream practice.","fatiha"],
["Dhikr","Remembering and mentioning Allah, including established phrases of praise and remembrance.","duas-dhikr"],
["Dua","Supplication: asking Allah for something or turning to Him in prayer.","duas-dhikr"],
["Salah","The formal ritual prayer performed at prescribed times.","salah"],
["Fajr","The dawn prayer, one of the five obligatory daily prayers.","prayer-times"],
["Dhuhr","The midday prayer, one of the five obligatory daily prayers.","prayer-times"],
["Asr","The afternoon prayer, one of the five obligatory daily prayers.","prayer-times"],
["Maghrib","The sunset prayer, one of the five obligatory daily prayers.","prayer-times"],
["Isha","The night prayer, one of the five obligatory daily prayers.","prayer-times"],
["Rak'ah","One complete cycle of prayer movements and recitation.","first-prayer"],
["Qiyam","Standing in prayer.","first-prayer"],
["Ruku","The bowing position in salah.","first-prayer"],
["Sujud","Prostration in salah.","first-prayer"],
["Tashahhud","The testimony and supplication recited while sitting in salah.","prayer-words"],
["Takbir","Saying Allahu akbar, especially in the movements of salah.","prayer-words"],
["Adhan","The call announcing the time of an obligatory prayer.","prayer-times"],
["Iqamah","The call made immediately before a congregational prayer begins.","jumuah"],
["Qiblah","The direction toward the Kaaba in Makkah faced during prayer.","qiblah"],
["Kaaba","The sacred House in Makkah toward which Muslims face when praying.","qiblah"],
["Wudu","A ritual purification performed with water before prayer and certain acts of worship.","wudu"],
["Ghusl","A full ritual bath required after particular states of major ritual impurity.","ghusl"],
["Tayammum","Dry purification using clean earth or its equivalent when water cannot be used under relevant conditions.","ghusl"],
["Niyyah","Intention: the purpose held in the heart for an act of worship.","prayer-prep"],
["Jumu'ah","The Friday congregational prayer that has specific rules and a sermon.","jumuah"],
["Masjid","Mosque; a place dedicated to Muslim prayer and community worship.","mosque"],
["Imam","A person who leads prayer; the term also has other scholarly meanings.","mosque"],
["Ummah","The wider community of Muslims.","community"],
["Ramadan","The ninth month of the Islamic lunar calendar, during which Muslims fast from dawn to sunset.","ramadan"],
["Sawm","Fasting, especially the prescribed fast of Ramadan.","fasting"],
["Iftar","The meal or moment at which the Ramadan fast is broken after sunset.","ramadan"],
["Suhoor","The pre-dawn meal taken before the Ramadan fast begins.","ramadan"],
["Zakah","Obligatory charity due on qualifying wealth when its conditions are met.","charity"],
["Sadaqah","Voluntary charity or an act of kindness offered for Allah's sake.","charity"],
["Nisab","A threshold of qualifying wealth used in zakah calculations.","charity"],
["Hajj","The pilgrimage to Makkah required once in a lifetime for those able to undertake it under the relevant conditions.","hajj"],
["Umrah","The lesser pilgrimage to Makkah involving a set of rites and which can be performed outside the Hajj season.","hajj"],
["Ihram","A sacred state entered for Hajj or Umrah with specific restrictions and rites.","hajj"],
["Halal","Permissible under Islamic guidance.","halal"],
["Haram","Prohibited under Islamic guidance.","halal"],
["Wajib","Often used for an obligatory duty; terminology can vary by legal school.","halal"],
["Fard","An obligatory duty; terminology and scope can be discussed differently among schools.","halal"],
["Mandub","Recommended or encouraged; terminology varies by legal school.","halal"],
["Makruh","Disliked; the exact legal classification differs by school and context.","halal"],
["Mubah","Permissible without a specific reward or sin attached to the act itself.","halal"],
["Fiqh","Islamic jurisprudence: the human scholarly effort to understand detailed rulings from the sources.","halal"],
["Madhhab","A recognised legal school, with methods and positions developed by scholars.","halal"],
["Ijtihad","Qualified scholarly reasoning used to derive or apply rulings where detailed interpretation is required.","halal"],
["Fatwa","A qualified scholarly legal answer to a question; it is not the same as revelation.","questions"],
["Ijma","Scholarly consensus in the technical legal sense; claims of consensus should be handled carefully.","questions"],
["Akhirah","The Hereafter and life after death.","belief"],
["Qiyamah","The Day of Resurrection and Judgment.","belief"],
["Qadr","Divine decree: Allah's knowledge and decree concerning creation; its details are studied within Islamic theology.","belief"],
["Angels","Created beings who obey Allah and perform roles described in revelation.","belief"],
["Jibril","The angel Gabriel, associated in revelation with communicating Allah's messages to prophets.","belief"],
["Tawbah","Repentance: turning back to Allah and seeking forgiveness after sin.","hard-days"],
["Sabr","Patience, perseverance, and steadfastness in obedience and hardship.","character"],
["Shukr","Gratitude to Allah expressed through the heart, speech, and action.","character"],
["Akhlaq","Character and conduct; the moral qualities a Muslim tries to cultivate.","character"],
["Adab","Proper manners, etiquette, and respectful conduct.","character"],
["Bid'ah","A technical term for religious innovation; its use and definition require careful scholarly context.","questions"],
["Eid al-Fitr","The festival marking the end of Ramadan.","eid"],
["Eid al-Adha","The festival during the Hajj season associated with sacrifice, worship, gratitude, and generosity.","eid"],
["Khutbah","A sermon, especially the Friday sermon and the Eid sermon.","jumuah"],
["Tajwid","Rules and disciplined methods for reciting Quran correctly.","reading-quran"],
["Tilawah","Recitation of the Quran.","reading-quran"],
["Tadabbur","Reflective contemplation of Quranic meaning.","reading-quran"],
["Matn","The wording or text of a hadith report.","sunnah"],
["Isnad","The chain of transmitters through whom a hadith report is narrated.","sunnah"],
["Shariah","The broad body of divine guidance in Islam; fiqh is the human understanding of detailed legal rulings.","halal"],
["Revert","A term some Muslims use for a person who embraces Islam; 'convert' is also widely used.","start"],
["New Muslim","A person who has recently entered Islam and is still building foundational knowledge and practice.","start"]
].map(([term,definition,lesson])=>({term,definition,lesson}));

export const duas=[
{title:"Before eating",arabic:"بِسْمِ اللَّهِ",transliteration:"Bismillah",meaning:"In the name of Allah.",context:"Say it before beginning to eat. If you forgot at first, use the established Sunnah wording when you remember.",source:"Sunnah reports concerning saying Allah's name before eating."},
{title:"After eating",arabic:"الْحَمْدُ لِلَّهِ",transliteration:"Alhamdulillah",meaning:"All praise and thanks belong to Allah.",context:"Use this remembrance to express gratitude after food and in ordinary moments of blessing.",source:"Established remembrance in the Sunnah."},
{title:"Ask Allah for knowledge",arabic:"رَبِّ زِدْنِي عِلْمًا",transliteration:"Rabbi zidni ilma",meaning:"My Lord, increase me in knowledge.",context:"A concise Quranic supplication that fits study, revision, and any moment when you want beneficial learning.",source:"Quran 20:114."},
{title:"Ask for good in both worlds",arabic:"رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",transliteration:"Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina adhaban-nar",meaning:"Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",context:"A broad supplication for wellbeing, goodness, and protection.",source:"Quran 2:201."},
{title:"Ask Allah for forgiveness",arabic:"أَسْتَغْفِرُ اللَّهَ",transliteration:"Astaghfirullah",meaning:"I seek Allah's forgiveness.",context:"A short phrase of repentance and turning back to Allah.",source:"Forgiveness and istighfar are repeatedly taught in Quran and Sunnah."},
{title:"Supplication of Yunus",arabic:"لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",transliteration:"La ilaha illa anta subhanaka inni kuntu minaz-zalimin",meaning:"There is no deity worthy of worship except You. Glory be to You. Indeed, I was among the wrongdoers.",context:"A powerful example of acknowledging Allah's oneness, glorifying Him, and admitting one's own fault.",source:"Quran 21:87."},
{title:"When worried about an outcome",arabic:"حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",transliteration:"Hasbunallahu wa ni'mal-wakil",meaning:"Allah is sufficient for us, and He is the best disposer of affairs.",context:"Remember Allah's sufficiency while also taking responsible practical steps.",source:"Quran 3:173."},
{title:"For parents",arabic:"رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",transliteration:"Rabbi irhamhuma kama rabbayani sagheera",meaning:"My Lord, have mercy upon them as they raised me when I was small.",context:"A Quranic prayer for mercy toward one's parents.",source:"Quran 17:24."},
{title:"For family and righteous homes",arabic:"رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",transliteration:"Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",meaning:"Our Lord, grant us from our spouses and children comfort to our eyes and make us an example for the mindful.",context:"A Quranic supplication about family wellbeing and righteous influence.",source:"Quran 25:74."},
{title:"Before sleep",arabic:"بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",transliteration:"Bismika Allahumma amutu wa ahya",meaning:"In Your name, O Allah, I die and I live.",context:"A brief Sunnah supplication to say before sleeping.",source:"Sahih al-Bukhari and Sahih Muslim."},
{title:"After waking",arabic:"الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",transliteration:"Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",meaning:"Praise is for Allah who gave us life after causing us to die, and to Him is the resurrection.",context:"A morning remembrance connecting waking with gratitude and the Hereafter.",source:"Sahih al-Bukhari and Sahih Muslim."},
{title:"Entering the toilet",arabic:"اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",transliteration:"Allahumma inni a'udhu bika minal-khubthi wal-khaba'ith",meaning:"O Allah, I seek refuge in You from male and female evil beings.",context:"A short Sunnah supplication said before entering the toilet.",source:"Sahih al-Bukhari and Sahih Muslim."},
{title:"Leaving the toilet",arabic:"غُفْرَانَكَ",transliteration:"Ghufranak",meaning:"I ask You for Your forgiveness.",context:"A concise Sunnah remembrance said after leaving the toilet.",source:"Sunan Abu Dawud, Jami' at-Tirmidhi, and other hadith collections."},
{title:"After wudu",arabic:"أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",transliteration:"Ashhadu alla ilaha illallahu wahdahu la sharika lah, wa ashhadu anna Muhammadan abduhu wa rasuluh",meaning:"I bear witness that there is no deity worthy of worship except Allah alone without partner, and I bear witness that Muhammad is His servant and Messenger.",context:"A well-known remembrance after completing wudu.",source:"Sahih Muslim and other hadith collections."},
{title:"Ask Allah for guidance and steadiness",arabic:"رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً إِنَّكَ أَنْتَ الْوَهَّابُ",transliteration:"Rabbana la tuzigh qulubana ba'da idh hadaytana wa hab lana milladunka rahmatan innaka antal-Wahhab",meaning:"Our Lord, do not let our hearts deviate after You have guided us, and grant us mercy from You. Surely You are the Bestower.",context:"A Quranic prayer for steadiness after guidance.",source:"Quran 3:8."},
{title:"Ask for ease",arabic:"رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",transliteration:"Rabbishrah li sadri wa yassir li amri",meaning:"My Lord, expand my chest for me and make my task easy for me.",context:"A Quranic supplication associated with Musa asking Allah for ease and clarity before a difficult task.",source:"Quran 20:25-26."}
] as const;